# Generated by Django 3.2.9 on 2023-06-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_home', models.BooleanField(default=False)),
                ('rated', models.BooleanField(default=False)),
                ('page_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Referance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
            ],
        ),
    ]
