# Generated by Django 3.2.9 on 2023-06-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='referance',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
