# Generated by Django 3.2.9 on 2023-07-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_referance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referance',
            name='image',
            field=models.CharField(default='static/blog/image/defaultreferancelogo.png', max_length=250),
        ),
    ]
