# Generated by Django 3.2.9 on 2023-07-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20230702_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(default='', max_length=250),
        ),
    ]
